### ISSUE TITLE
Rust nightly build fails due to unsafe libc call

### ISSUE THREAD

**Issue by rkowalewski** [semarie/build-rust#18]
Hello,

you recent fixed an issue due to an unsafe libc call in rust-lang/libc#2035.

Can you tell me how to use the libc master branch in the Rust nightly build? The current bootstrap config seems to use tag 0.2.79.
I am kind of new to Rust, so I am not very familiar with its toolchain.

**Comment by semarie** [comment]
it isn't possible simply.

the PR is only a first step. the full correction needs a libc release (asked in rust-lang/libc#2038) and update rust repository to use the newer libc version.

**Comment by rkowalewski** [comment]
Thank you for the quick response. Then I just need to wait.

**Comment by semarie** [comment]
Now that a libc version has been released with the fix, I made PR https://github.com/rust-lang/rust/pull/81464 for use it in rustc.

**Comment by rkowalewski** [comment]
Thank you for taking care on this.

**Comment by rkowalewski** [comment]
While the original issue described here is resolved, there is a follow-up one.

I submitted it to rust-lang/rust#81787. Is this issue specific to the way how we build rust on OpenBSD? Or is it possible to skip some tools like `rustfmt` when building `rustc`? If this issue is not specific to our toolchain on OpenBSD, please just close the issue here.

See my attached [build.log](https://github.com/semarie/build-rust/files/5938797/build.log)

**Comment by semarie** [comment]
it is, currently, an expected failure. See the [rust-toolstate](https://rust-lang-nursery.github.io/rust-toolstate/) page: it mentions rustfmt and rls are currently failing in official builds.

to customize the build, see the [config.toml](https://github.com/rust-lang/rust/blob/master/config.toml.example) file inside the build directory, specially the `build.tools` directive. You might need to patch `build.sh` to avoid it overrides your customization.

**Comment by semarie** [comment]
oh, and please to not reopen this issue if your problem isn't related to this issue. create a new issue for a new problem.

**Comment by rkowalewski** [comment]
I initially thought about opening a new issue but first wanted to know if it is the right place here. Sorry for the circumstances.
