### ISSUE TITLE
How to get newer version of rustc (1.77 or 1.79)

### ISSUE THREAD

**Issue by FrankReh** [semarie/build-rust#27]
Hi. Wonderful script. With it, I could get rustc and cargo running on OpenBSD 7.5 and get some very large Rust projects compiled already.

But one project I want to build requires rustc 1.77 or higher, and even trying to get a new version of `cargo` built with the command `cargo install cargo` fails, because the rustc that is built is version 1.76 and the error indicates 1.77 or high is required also.

Does someone know what's involved in getting 1.77 or maybe 1.79 built?

**Comment by semarie** [comment]
the script is building rustc/cargo nightly version, so currently it is upcoming `1.81.0-nightly`. so if you have using it, you already have such version.

you should have something like the following, when running `rustc -vV`:
```
$ path/to/nighty/bin/rustc -vV
rustc 1.81.0-nightly (4bc39f028 2024-06-26) (built from a source tarball)
binary: rustc
commit-hash: 4bc39f028d14c24b04dd17dc425432c6ec354536
commit-date: 2024-06-26
host: x86_64-unknown-openbsd
release: 1.81.0-nightly
LLVM version: 17.0.6
```

**Comment by FrankReh** [comment]
I guess the script didn't complete for me before but I didn't notice. Today I created a new machine with more disk and more RAM and ran the build.sh {init, nightly} again. But the script fails indicating 1.76.0 isn't recent enough now.

```
    Finished dev [unoptimized] target(s) in 8m 11s
running: /home/frank/rs/build_dir/build/bootstrap/debug/bootstrap --config /home/frank/rs/build_dir/config.toml --build-dir /home/frank/rs/build_dir/build dist --jobs=4


Unexpected rustc version: 1.76.0, we should use 1.79.x/1.80.0 to build source with 1.80.0


Traceback (most recent call last):
  File "/home/frank/rs/build_dir/rustc-beta-src/x.py", line 50, in <module>
    bootstrap.main()
  File "/home/frank/rs/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 1191, in main
    bootstrap(args)
  File "/home/frank/rs/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 1167, in bootstrap
    run(args, env=env, verbose=build.verbose, is_bootstrap=True)
  File "/home/frank/rs/build_dir/rustc-beta-src/src/bootstrap/bootstrap.py", line 186, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /home/frank/rs/build_dir/build/bootstrap/debug/bootstrap --config /home/frank/rs/build_dir/config.toml --build-dir /home/frank/rs/build_dir/build dist --jobs=4
Fri Jun 28 15:56:06 EDT 2024: task not finished: see build.log for detail
```

Can I change the build.sh script to try and pull in an earlier nightly that would have still built with 1.76?

Thanks.

**Comment by FrankReh** [comment]
I'm trying to modify a local version of build.sh to allow for a 1.77.0 target, which should be buildable from 1.76.0. If it can be built, then once it is added to the PATH, I hope to get beta and nightly building again. But the changes I have so far are a bit of a hodge-podge. But I found the src at `https://static.rust-lang.org/dist/2024-03-21/rustc-1.77.0-src.tar.gz`. There's no stage0 file any longer. Now it's a stage0.json file, but I guess I can comment out the grep line that was showing the required compiler.

My OpenBSD is just a VirtualBox VM for now so is super slow for anything HD related.

**Comment by semarie** [comment]
the script is intent to be run on OpenBSD -current (a snapshot) and not on a OpenBSD -release.

modifying the build script is possible. you could also look at previous versions of the script (regarding stage0 file changes), but your are your own. good luck !
