### ISSUE TITLE
Building stable does not work.

### ISSUE THREAD

**Issue by jan-schreib** [semarie/build-rust#8]
Errors out with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /usr/obj/ports/rust-1.23.0/rustc-1.23.0-src/src/libcore/result.rs:906:4
```

Maybe an upstream issue?

**Comment by semarie** [comment]
this tool isn't for building stable, but only beta or nightly rust build.
please note it requires release to release patches.

currently, the beta (1.24) build doesn't work due to missing patches for OpenBSD.

**Comment by jan-schreib** [comment]
Sry, typo on my side. I meant beta ofc. Ok, thanks for the info!

**Comment by semarie** [comment]
I am updating the patches. beta should be buildable now. nightly is still in processing.
